# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - link_1_joint
    - link_2_joint
    - link_3_joint
    - link_4_joint
    - link_5_joint
    - robotiq_85_left_knuckle_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_trajectory:
  type: position_controllers/JointTrajectoryController
  joints:
    - link_1_joint
    - link_2_joint
    - link_3_joint
    - link_4_joint
    - link_5_joint
  gains:
    link_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
# gripper_trajectory:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - robotiq_85_left_knuckle_joint
#   gains:
#     robotiq_85_left_knuckle_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# Gripper controller
gripper_controller:
  type: position_controllers/GripperActionController
  joint: robotiq_85_left_knuckle_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0
