controller_list:
  - name: fake_brabo_arm_controller
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - link_4_joint
      - link_5_joint
  - name: fake_brabo_gripper_controller
    joints:
      - robotiq_85_left_knuckle_joint