brabo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: link_1_joint
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: link_2_joint
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: link_3_joint
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: link_4_joint
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: link_5_joint

  # Gripper controller
  gripper_controller:
    type: position_controllers/GripperActionController
    joint: robotiq_85_left_knuckle_joint
    action_monitor_rate: 20
    goal_tolerance: 0.002
    max_effort: 100
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0

